# fly.toml app configuration file generated for wordservice on 2025-01-28T22:08:27+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wordservice'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
